/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yctimes_autocamera_BarCodeDecoder */

#ifndef _Included_com_yctimes_autocamera_BarCodeDecoder
#define _Included_com_yctimes_autocamera_BarCodeDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yctimes_autocamera_BarCodeDecoder
 * Method:    doDecode
 * Signature: ([III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yctimes_autocamera_BarCodeDecoder_doDecode___3III
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_yctimes_autocamera_BarCodeDecoder
 * Method:    doDecode
 * Signature: (Landroid/graphics/Bitmap;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yctimes_autocamera_BarCodeDecoder_doDecode__Landroid_graphics_Bitmap_2
  (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
